# This file was generated by attributes::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_int <- function(x) {
    .Call('RcppTest_as_int', PACKAGE = 'RcppTest', x)
}

as_double <- function(x) {
    .Call('RcppTest_as_double', PACKAGE = 'RcppTest', x)
}

as_raw <- function(x) {
    .Call('RcppTest_as_raw', PACKAGE = 'RcppTest', x)
}

as_bool <- function(x) {
    .Call('RcppTest_as_bool', PACKAGE = 'RcppTest', x)
}

as_string <- function(x) {
    .Call('RcppTest_as_string', PACKAGE = 'RcppTest', x)
}

as_vector_int <- function(x) {
    .Call('RcppTest_as_vector_int', PACKAGE = 'RcppTest', x)
}

as_vector_double <- function(x) {
    .Call('RcppTest_as_vector_double', PACKAGE = 'RcppTest', x)
}

as_vector_raw <- function(x) {
    .Call('RcppTest_as_vector_raw', PACKAGE = 'RcppTest', x)
}

as_vector_bool <- function(x) {
    .Call('RcppTest_as_vector_bool', PACKAGE = 'RcppTest', x)
}

as_vector_string <- function(x) {
    .Call('RcppTest_as_vector_string', PACKAGE = 'RcppTest', x)
}

as_deque_int <- function(x) {
    .Call('RcppTest_as_deque_int', PACKAGE = 'RcppTest', x)
}

as_list_int <- function(x) {
    .Call('RcppTest_as_list_int', PACKAGE = 'RcppTest', x)
}

FromSEXP <- function(x) {
    .Call('RcppTest_FromSEXP', PACKAGE = 'RcppTest', x)
}

index_byName <- function(df, s) {
    .Call('RcppTest_index_byName', PACKAGE = 'RcppTest', df, s)
}

index_byPosition <- function(df, i) {
    .Call('RcppTest_index_byPosition', PACKAGE = 'RcppTest', df, i)
}

string_element <- function(df) {
    .Call('RcppTest_string_element', PACKAGE = 'RcppTest', df)
}

createOne <- function() {
    .Call('RcppTest_createOne', PACKAGE = 'RcppTest')
}

createTwo <- function() {
    .Call('RcppTest_createTwo', PACKAGE = 'RcppTest')
}

SlotProxy <- function(o, yy) {
    .Call('RcppTest_SlotProxy', PACKAGE = 'RcppTest', o, yy)
}

AttributeProxy <- function(o, y) {
    .Call('RcppTest_AttributeProxy', PACKAGE = 'RcppTest', o, y)
}

createTwoStringsAsFactors <- function() {
    .Call('RcppTest_createTwoStringsAsFactors', PACKAGE = 'RcppTest')
}

DataFrame_nrows <- function(df) {
    .Call('RcppTest_DataFrame_nrows', PACKAGE = 'RcppTest', df)
}

DataFrame_proxies <- function(df) {
    .Call('RcppTest_DataFrame_proxies', PACKAGE = 'RcppTest', df)
}

runit_ls <- function(env) {
    .Call('RcppTest_runit_ls', PACKAGE = 'RcppTest', env)
}

runit_ls2 <- function(env) {
    .Call('RcppTest_runit_ls2', PACKAGE = 'RcppTest', env)
}

runit_get <- function(env, name) {
    .Call('RcppTest_runit_get', PACKAGE = 'RcppTest', env, name)
}

runit_exists <- function(env, st) {
    .Call('RcppTest_runit_exists', PACKAGE = 'RcppTest', env, st)
}

runit_assign <- function(env, st, object) {
    .Call('RcppTest_runit_assign', PACKAGE = 'RcppTest', env, st, object)
}

runit_islocked <- function(env) {
    invisible(.Call('RcppTest_runit_islocked', PACKAGE = 'RcppTest', env))
}

runit_bindingIsActive <- function(env, st) {
    .Call('RcppTest_runit_bindingIsActive', PACKAGE = 'RcppTest', env, st)
}

runit_bindingIsLocked <- function(env, st) {
    .Call('RcppTest_runit_bindingIsLocked', PACKAGE = 'RcppTest', env, st)
}

runit_notanenv <- function(x) {
    invisible(.Call('RcppTest_runit_notanenv', PACKAGE = 'RcppTest', x))
}

runit_lockbinding <- function(env, st) {
    invisible(.Call('RcppTest_runit_lockbinding', PACKAGE = 'RcppTest', env, st))
}

runit_unlockbinding <- function(env, st) {
    invisible(.Call('RcppTest_runit_unlockbinding', PACKAGE = 'RcppTest', env, st))
}

runit_globenv <- function() {
    .Call('RcppTest_runit_globenv', PACKAGE = 'RcppTest')
}

runit_emptyenv <- function() {
    .Call('RcppTest_runit_emptyenv', PACKAGE = 'RcppTest')
}

runit_baseenv <- function() {
    .Call('RcppTest_runit_baseenv', PACKAGE = 'RcppTest')
}

runit_namespace <- function(st) {
    .Call('RcppTest_runit_namespace', PACKAGE = 'RcppTest', st)
}

runit_env_SEXP <- function(env) {
    .Call('RcppTest_runit_env_SEXP', PACKAGE = 'RcppTest', env)
}

runit_env_string <- function(st) {
    .Call('RcppTest_runit_env_string', PACKAGE = 'RcppTest', st)
}

runit_env_int <- function(pos) {
    .Call('RcppTest_runit_env_int', PACKAGE = 'RcppTest', pos)
}

runit_parent <- function(env) {
    .Call('RcppTest_runit_parent', PACKAGE = 'RcppTest', env)
}

runit_remove <- function(env, name) {
    .Call('RcppTest_runit_remove', PACKAGE = 'RcppTest', env, name)
}

runit_square <- function(e) {
    .Call('RcppTest_runit_square', PACKAGE = 'RcppTest', e)
}

runit_child <- function() {
    .Call('RcppTest_runit_child', PACKAGE = 'RcppTest')
}

function_ <- function(x) {
    .Call('RcppTest_function_', PACKAGE = 'RcppTest', x)
}

function_variadic <- function(sort, y) {
    .Call('RcppTest_function_variadic', PACKAGE = 'RcppTest', sort, y)
}

function_env <- function(fun) {
    .Call('RcppTest_function_env', PACKAGE = 'RcppTest', fun)
}

function_namespace_env <- function() {
    .Call('RcppTest_function_namespace_env', PACKAGE = 'RcppTest')
}

runit_language <- function(x) {
    .Call('RcppTest_runit_language', PACKAGE = 'RcppTest', x)
}

runit_lang_variadic_1 <- function() {
    .Call('RcppTest_runit_lang_variadic_1', PACKAGE = 'RcppTest')
}

runit_lang_variadic_2 <- function() {
    .Call('RcppTest_runit_lang_variadic_2', PACKAGE = 'RcppTest')
}

runit_lang_push_back <- function() {
    .Call('RcppTest_runit_lang_push_back', PACKAGE = 'RcppTest')
}

runit_lang_square_rv <- function() {
    .Call('RcppTest_runit_lang_square_rv', PACKAGE = 'RcppTest')
}

runit_lang_square_lv <- function() {
    .Call('RcppTest_runit_lang_square_lv', PACKAGE = 'RcppTest')
}

runit_lang_fun <- function(fun, x) {
    .Call('RcppTest_runit_lang_fun', PACKAGE = 'RcppTest', fun, x)
}

runit_lang_inenv <- function(env) {
    .Call('RcppTest_runit_lang_inenv', PACKAGE = 'RcppTest', env)
}

runit_pairlist <- function(x) {
    .Call('RcppTest_runit_pairlist', PACKAGE = 'RcppTest', x)
}

runit_pl_variadic_1 <- function() {
    .Call('RcppTest_runit_pl_variadic_1', PACKAGE = 'RcppTest')
}

runit_pl_variadic_2 <- function() {
    .Call('RcppTest_runit_pl_variadic_2', PACKAGE = 'RcppTest')
}

runit_pl_push_front <- function() {
    .Call('RcppTest_runit_pl_push_front', PACKAGE = 'RcppTest')
}

runit_pl_push_back <- function() {
    .Call('RcppTest_runit_pl_push_back', PACKAGE = 'RcppTest')
}

runit_pl_insert <- function() {
    .Call('RcppTest_runit_pl_insert', PACKAGE = 'RcppTest')
}

runit_pl_replace <- function() {
    .Call('RcppTest_runit_pl_replace', PACKAGE = 'RcppTest')
}

runit_pl_size <- function() {
    .Call('RcppTest_runit_pl_size', PACKAGE = 'RcppTest')
}

runit_pl_remove_1 <- function() {
    .Call('RcppTest_runit_pl_remove_1', PACKAGE = 'RcppTest')
}

runit_pl_remove_2 <- function() {
    .Call('RcppTest_runit_pl_remove_2', PACKAGE = 'RcppTest')
}

runit_pl_remove_3 <- function() {
    .Call('RcppTest_runit_pl_remove_3', PACKAGE = 'RcppTest')
}

runit_pl_square_1 <- function() {
    .Call('RcppTest_runit_pl_square_1', PACKAGE = 'RcppTest')
}

runit_pl_square_2 <- function() {
    .Call('RcppTest_runit_pl_square_2', PACKAGE = 'RcppTest')
}

runit_formula_ <- function() {
    .Call('RcppTest_runit_formula_', PACKAGE = 'RcppTest')
}

runit_formula_SEXP <- function(form) {
    .Call('RcppTest_runit_formula_SEXP', PACKAGE = 'RcppTest', form)
}

matrix_numeric <- function(m) {
    .Call('RcppTest_matrix_numeric', PACKAGE = 'RcppTest', m)
}

matrix_character <- function(m) {
    .Call('RcppTest_matrix_character', PACKAGE = 'RcppTest', m)
}

matrix_generic <- function(m) {
    .Call('RcppTest_matrix_generic', PACKAGE = 'RcppTest', m)
}

matrix_numeric_ctor2 <- function() {
    .Call('RcppTest_matrix_numeric_ctor2', PACKAGE = 'RcppTest')
}

integer_matrix_indexing <- function(m) {
    .Call('RcppTest_integer_matrix_indexing', PACKAGE = 'RcppTest', m)
}

integer_matrix_indexing_lhs <- function(m) {
    .Call('RcppTest_integer_matrix_indexing_lhs', PACKAGE = 'RcppTest', m)
}

runit_NumericMatrix_row <- function(m) {
    .Call('RcppTest_runit_NumericMatrix_row', PACKAGE = 'RcppTest', m)
}

runit_CharacterMatrix_row <- function(m) {
    .Call('RcppTest_runit_CharacterMatrix_row', PACKAGE = 'RcppTest', m)
}

runit_NumericMatrix_column <- function(m) {
    .Call('RcppTest_runit_NumericMatrix_column', PACKAGE = 'RcppTest', m)
}

runit_NumericMatrix_cumsum <- function(input) {
    .Call('RcppTest_runit_NumericMatrix_cumsum', PACKAGE = 'RcppTest', input)
}

runit_CharacterMatrix_column <- function(m) {
    .Call('RcppTest_runit_CharacterMatrix_column', PACKAGE = 'RcppTest', m)
}

runit_Row_Column_sugar <- function(x) {
    .Call('RcppTest_runit_Row_Column_sugar', PACKAGE = 'RcppTest', x)
}

runit_NumericMatrix_colsum <- function(input) {
    .Call('RcppTest_runit_NumericMatrix_colsum', PACKAGE = 'RcppTest', input)
}

runit_NumericMatrix_rowsum <- function(input) {
    .Call('RcppTest_runit_NumericMatrix_rowsum', PACKAGE = 'RcppTest', input)
}

character_matrix_indexing <- function(m) {
    .Call('RcppTest_character_matrix_indexing', PACKAGE = 'RcppTest', m)
}

character_matrix_indexing_lhs <- function(m) {
    .Call('RcppTest_character_matrix_indexing_lhs', PACKAGE = 'RcppTest', m)
}

character_matrix_row_iteration_incr <- function(m) {
    .Call('RcppTest_character_matrix_row_iteration_incr', PACKAGE = 'RcppTest', m)
}

character_matrix_row_iteration_decr <- function(m) {
    .Call('RcppTest_character_matrix_row_iteration_decr', PACKAGE = 'RcppTest', m)
}

symbol_ <- function() {
    .Call('RcppTest_symbol_', PACKAGE = 'RcppTest')
}

symbol_ctor <- function(x) {
    .Call('RcppTest_symbol_ctor', PACKAGE = 'RcppTest', x)
}

Argument_ <- function() {
    .Call('RcppTest_Argument_', PACKAGE = 'RcppTest')
}

evaluator_error <- function() {
    .Call('RcppTest_evaluator_error', PACKAGE = 'RcppTest')
}

evaluator_ok <- function(x) {
    .Call('RcppTest_evaluator_ok', PACKAGE = 'RcppTest', x)
}

exceptions_ <- function() {
    invisible(.Call('RcppTest_exceptions_', PACKAGE = 'RcppTest'))
}

has_iterator_ <- function() {
    .Call('RcppTest_has_iterator_', PACKAGE = 'RcppTest')
}

na_proxy <- function() {
    .Call('RcppTest_na_proxy', PACKAGE = 'RcppTest')
}

stretchy_list <- function() {
    .Call('RcppTest_stretchy_list', PACKAGE = 'RcppTest')
}

named_stretchy_list <- function() {
    .Call('RcppTest_named_stretchy_list', PACKAGE = 'RcppTest')
}

runit_Reference_getId <- function(obj) {
    .Call('RcppTest_runit_Reference_getId', PACKAGE = 'RcppTest', obj)
}

plus_REALSXP <- function() {
    .Call('RcppTest_plus_REALSXP', PACKAGE = 'RcppTest')
}

times_REALSXP <- function() {
    .Call('RcppTest_times_REALSXP', PACKAGE = 'RcppTest')
}

divides_REALSXP <- function() {
    .Call('RcppTest_divides_REALSXP', PACKAGE = 'RcppTest')
}

minus_REALSXP <- function() {
    .Call('RcppTest_minus_REALSXP', PACKAGE = 'RcppTest')
}

functions_REALSXP <- function() {
    .Call('RcppTest_functions_REALSXP', PACKAGE = 'RcppTest')
}

S4_methods <- function(y) {
    .Call('RcppTest_S4_methods', PACKAGE = 'RcppTest', y)
}

S4_getslots <- function(y) {
    invisible(.Call('RcppTest_S4_getslots', PACKAGE = 'RcppTest', y))
}

S4_setslots <- function(y) {
    invisible(.Call('RcppTest_S4_setslots', PACKAGE = 'RcppTest', y))
}

S4_setslots_2 <- function(y) {
    invisible(.Call('RcppTest_S4_setslots_2', PACKAGE = 'RcppTest', y))
}

S4_ctor <- function(cl) {
    .Call('RcppTest_S4_ctor', PACKAGE = 'RcppTest', cl)
}

S4_is_track <- function(tr) {
    .Call('RcppTest_S4_is_track', PACKAGE = 'RcppTest', tr)
}

S4_is_trackCurve <- function(tr) {
    .Call('RcppTest_S4_is_trackCurve', PACKAGE = 'RcppTest', tr)
}

S4_get_slot_x <- function(o) {
    .Call('RcppTest_S4_get_slot_x', PACKAGE = 'RcppTest', o)
}

S4_get_attr_x <- function(o) {
    .Call('RcppTest_S4_get_attr_x', PACKAGE = 'RcppTest', o)
}

S4_dotdata <- function(foo) {
    .Call('RcppTest_S4_dotdata', PACKAGE = 'RcppTest', foo)
}

countArgs <- function(...) {
    .Call('RcppTest_countArgs', PACKAGE = 'RcppTest', environment())
}

countNamedArgs <- function(...) {
    .Call('RcppTest_countNamedArgs', PACKAGE = 'RcppTest', environment())
}

wrap_lazy_vector <- function() {
    .Call('RcppTest_wrap_lazy_vector', PACKAGE = 'RcppTest')
}

Rcpp_IsNA <- function(x) {
    .Call('RcppTest_Rcpp_IsNA', PACKAGE = 'RcppTest', x)
}

Rcpp_IsNaN <- function(x) {
    .Call('RcppTest_Rcpp_IsNaN', PACKAGE = 'RcppTest', x)
}

runit_dnorm <- function(x, a, b) {
    .Call('RcppTest_runit_dnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_pnorm <- function(x, a, b) {
    .Call('RcppTest_runit_pnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_qnorm <- function(x, a, b) {
    .Call('RcppTest_runit_qnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_dunif <- function(x, a, b) {
    .Call('RcppTest_runit_dunif', PACKAGE = 'RcppTest', x, a, b)
}

runit_punif <- function(x, a, b) {
    .Call('RcppTest_runit_punif', PACKAGE = 'RcppTest', x, a, b)
}

runit_qunif <- function(x, a, b) {
    .Call('RcppTest_runit_qunif', PACKAGE = 'RcppTest', x, a, b)
}

runit_dgamma <- function(x, a, b) {
    .Call('RcppTest_runit_dgamma', PACKAGE = 'RcppTest', x, a, b)
}

runit_pgamma <- function(x, a, b) {
    .Call('RcppTest_runit_pgamma', PACKAGE = 'RcppTest', x, a, b)
}

runit_qgamma <- function(x, a, b) {
    .Call('RcppTest_runit_qgamma', PACKAGE = 'RcppTest', x, a, b)
}

runit_dbeta <- function(x, a, b) {
    .Call('RcppTest_runit_dbeta', PACKAGE = 'RcppTest', x, a, b)
}

runit_pbeta <- function(x, a, b) {
    .Call('RcppTest_runit_pbeta', PACKAGE = 'RcppTest', x, a, b)
}

runit_qbeta <- function(x, a, b) {
    .Call('RcppTest_runit_qbeta', PACKAGE = 'RcppTest', x, a, b)
}

runit_dlnorm <- function(x, a, b) {
    .Call('RcppTest_runit_dlnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_plnorm <- function(x, a, b) {
    .Call('RcppTest_runit_plnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_qlnorm <- function(x, a, b) {
    .Call('RcppTest_runit_qlnorm', PACKAGE = 'RcppTest', x, a, b)
}

runit_dchisq <- function(x, a) {
    .Call('RcppTest_runit_dchisq', PACKAGE = 'RcppTest', x, a)
}

runit_pchisq <- function(x, a) {
    .Call('RcppTest_runit_pchisq', PACKAGE = 'RcppTest', x, a)
}

runit_qchisq <- function(x, a) {
    .Call('RcppTest_runit_qchisq', PACKAGE = 'RcppTest', x, a)
}

runit_dnchisq <- function(x, a, b) {
    .Call('RcppTest_runit_dnchisq', PACKAGE = 'RcppTest', x, a, b)
}

runit_pnchisq <- function(x, a, b) {
    .Call('RcppTest_runit_pnchisq', PACKAGE = 'RcppTest', x, a, b)
}

runit_qnchisq <- function(x, a, b) {
    .Call('RcppTest_runit_qnchisq', PACKAGE = 'RcppTest', x, a, b)
}

runit_df <- function(x, a, b) {
    .Call('RcppTest_runit_df', PACKAGE = 'RcppTest', x, a, b)
}

runit_pf <- function(x, a, b) {
    .Call('RcppTest_runit_pf', PACKAGE = 'RcppTest', x, a, b)
}

runit_qf <- function(x, a, b) {
    .Call('RcppTest_runit_qf', PACKAGE = 'RcppTest', x, a, b)
}

runit_dt <- function(x, a) {
    .Call('RcppTest_runit_dt', PACKAGE = 'RcppTest', x, a)
}

runit_pt <- function(x, a) {
    .Call('RcppTest_runit_pt', PACKAGE = 'RcppTest', x, a)
}

runit_qt <- function(x, a) {
    .Call('RcppTest_runit_qt', PACKAGE = 'RcppTest', x, a)
}

runit_dbinom <- function(x, a, b) {
    .Call('RcppTest_runit_dbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_pbinom <- function(x, a, b) {
    .Call('RcppTest_runit_pbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_qbinom <- function(x, a, b) {
    .Call('RcppTest_runit_qbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_dcauchy <- function(x, a, b) {
    .Call('RcppTest_runit_dcauchy', PACKAGE = 'RcppTest', x, a, b)
}

runit_pcauchy <- function(x, a, b) {
    .Call('RcppTest_runit_pcauchy', PACKAGE = 'RcppTest', x, a, b)
}

runit_qcauchy <- function(x, a, b) {
    .Call('RcppTest_runit_qcauchy', PACKAGE = 'RcppTest', x, a, b)
}

runit_dexp <- function(x, a) {
    .Call('RcppTest_runit_dexp', PACKAGE = 'RcppTest', x, a)
}

runit_pexp <- function(x, a) {
    .Call('RcppTest_runit_pexp', PACKAGE = 'RcppTest', x, a)
}

runit_qexp <- function(x, a) {
    .Call('RcppTest_runit_qexp', PACKAGE = 'RcppTest', x, a)
}

runit_dgeom <- function(x, a) {
    .Call('RcppTest_runit_dgeom', PACKAGE = 'RcppTest', x, a)
}

runit_pgeom <- function(x, a) {
    .Call('RcppTest_runit_pgeom', PACKAGE = 'RcppTest', x, a)
}

runit_qgeom <- function(x, a) {
    .Call('RcppTest_runit_qgeom', PACKAGE = 'RcppTest', x, a)
}

runit_dhyper <- function(x, a, b, c) {
    .Call('RcppTest_runit_dhyper', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_phyper <- function(x, a, b, c) {
    .Call('RcppTest_runit_phyper', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_qhyper <- function(x, a, b, c) {
    .Call('RcppTest_runit_qhyper', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_dnbinom <- function(x, a, b) {
    .Call('RcppTest_runit_dnbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_pnbinom <- function(x, a, b) {
    .Call('RcppTest_runit_pnbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_qnbinom <- function(x, a, b) {
    .Call('RcppTest_runit_qnbinom', PACKAGE = 'RcppTest', x, a, b)
}

runit_dpois <- function(x, a) {
    .Call('RcppTest_runit_dpois', PACKAGE = 'RcppTest', x, a)
}

runit_ppois <- function(x, a) {
    .Call('RcppTest_runit_ppois', PACKAGE = 'RcppTest', x, a)
}

runit_qpois <- function(x, a) {
    .Call('RcppTest_runit_qpois', PACKAGE = 'RcppTest', x, a)
}

runit_dweibull <- function(x, a, b) {
    .Call('RcppTest_runit_dweibull', PACKAGE = 'RcppTest', x, a, b)
}

runit_pweibull <- function(x, a, b) {
    .Call('RcppTest_runit_pweibull', PACKAGE = 'RcppTest', x, a, b)
}

runit_qweibull <- function(x, a, b) {
    .Call('RcppTest_runit_qweibull', PACKAGE = 'RcppTest', x, a, b)
}

runit_dlogis <- function(x, a, b) {
    .Call('RcppTest_runit_dlogis', PACKAGE = 'RcppTest', x, a, b)
}

runit_plogis <- function(x, a, b) {
    .Call('RcppTest_runit_plogis', PACKAGE = 'RcppTest', x, a, b)
}

runit_qlogis <- function(x, a, b) {
    .Call('RcppTest_runit_qlogis', PACKAGE = 'RcppTest', x, a, b)
}

runit_dnbeta <- function(x, a, b, c) {
    .Call('RcppTest_runit_dnbeta', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_pnbeta <- function(x, a, b, c) {
    .Call('RcppTest_runit_pnbeta', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_qnbeta <- function(x, a, b, c) {
    .Call('RcppTest_runit_qnbeta', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_dnf <- function(x, a, b, c) {
    .Call('RcppTest_runit_dnf', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_pnf <- function(x, a, b, c) {
    .Call('RcppTest_runit_pnf', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_qnf <- function(x, a, b, c) {
    .Call('RcppTest_runit_qnf', PACKAGE = 'RcppTest', x, a, b, c)
}

runit_dnt <- function(x, a, b) {
    .Call('RcppTest_runit_dnt', PACKAGE = 'RcppTest', x, a, b)
}

runit_pnt <- function(x, a, b) {
    .Call('RcppTest_runit_pnt', PACKAGE = 'RcppTest', x, a, b)
}

runit_qnt <- function(x, a, b) {
    .Call('RcppTest_runit_qnt', PACKAGE = 'RcppTest', x, a, b)
}

runit_dwilcox <- function(x, a, b) {
    .Call('RcppTest_runit_dwilcox', PACKAGE = 'RcppTest', x, a, b)
}

runit_pwilcox <- function(x, a, b) {
    .Call('RcppTest_runit_pwilcox', PACKAGE = 'RcppTest', x, a, b)
}

runit_qwilcox <- function(x, a, b) {
    .Call('RcppTest_runit_qwilcox', PACKAGE = 'RcppTest', x, a, b)
}

runit_dbeta_2 <- function(xx, aa, bb) {
    .Call('RcppTest_runit_dbeta_2', PACKAGE = 'RcppTest', xx, aa, bb)
}

runit_dbinom_2 <- function(xx) {
    .Call('RcppTest_runit_dbinom_2', PACKAGE = 'RcppTest', xx)
}

runit_dunif_2 <- function(xx) {
    .Call('RcppTest_runit_dunif_2', PACKAGE = 'RcppTest', xx)
}

runit_dgamma_2 <- function(xx) {
    .Call('RcppTest_runit_dgamma_2', PACKAGE = 'RcppTest', xx)
}

runit_dpois_2 <- function(xx) {
    .Call('RcppTest_runit_dpois_2', PACKAGE = 'RcppTest', xx)
}

runit_dnorm_2 <- function(xx) {
    .Call('RcppTest_runit_dnorm_2', PACKAGE = 'RcppTest', xx)
}

runit_dt_2 <- function(xx) {
    .Call('RcppTest_runit_dt_2', PACKAGE = 'RcppTest', xx)
}

runit_pbeta_2 <- function(xx, aa, bb) {
    .Call('RcppTest_runit_pbeta_2', PACKAGE = 'RcppTest', xx, aa, bb)
}

runit_pbinom_2 <- function(xx, n, p) {
    .Call('RcppTest_runit_pbinom_2', PACKAGE = 'RcppTest', xx, n, p)
}

runit_pcauchy_2 <- function(xx, loc, scl) {
    .Call('RcppTest_runit_pcauchy_2', PACKAGE = 'RcppTest', xx, loc, scl)
}

runit_punif_2 <- function(xx) {
    .Call('RcppTest_runit_punif_2', PACKAGE = 'RcppTest', xx)
}

runit_pgamma_2 <- function(xx) {
    .Call('RcppTest_runit_pgamma_2', PACKAGE = 'RcppTest', xx)
}

runit_pnf_2 <- function(xx) {
    .Call('RcppTest_runit_pnf_2', PACKAGE = 'RcppTest', xx)
}

runit_pf_2 <- function(xx) {
    .Call('RcppTest_runit_pf_2', PACKAGE = 'RcppTest', xx)
}

runit_pnchisq_2 <- function(xx) {
    .Call('RcppTest_runit_pnchisq_2', PACKAGE = 'RcppTest', xx)
}

runit_pchisq_2 <- function(xx) {
    .Call('RcppTest_runit_pchisq_2', PACKAGE = 'RcppTest', xx)
}

runit_pnorm_2 <- function(xx) {
    .Call('RcppTest_runit_pnorm_2', PACKAGE = 'RcppTest', xx)
}

runit_ppois_2 <- function(xx) {
    .Call('RcppTest_runit_ppois_2', PACKAGE = 'RcppTest', xx)
}

runit_pt_2 <- function(xx) {
    .Call('RcppTest_runit_pt_2', PACKAGE = 'RcppTest', xx)
}

runit_pnt_2 <- function(xx) {
    .Call('RcppTest_runit_pnt_2', PACKAGE = 'RcppTest', xx)
}

runit_qbinom_prob <- function(xx, n, p) {
    .Call('RcppTest_runit_qbinom_prob', PACKAGE = 'RcppTest', xx, n, p)
}

runit_qunif_prob <- function(xx) {
    .Call('RcppTest_runit_qunif_prob', PACKAGE = 'RcppTest', xx)
}

runit_qnorm_prob <- function(xx) {
    .Call('RcppTest_runit_qnorm_prob', PACKAGE = 'RcppTest', xx)
}

runit_qnorm_log <- function(xx) {
    .Call('RcppTest_runit_qnorm_log', PACKAGE = 'RcppTest', xx)
}

runit_qpois_prob <- function(xx) {
    .Call('RcppTest_runit_qpois_prob', PACKAGE = 'RcppTest', xx)
}

runit_qt_2 <- function(xx, d, lt, lg) {
    .Call('RcppTest_runit_qt_2', PACKAGE = 'RcppTest', xx, d, lt, lg)
}

asDouble <- function(d) {
    .Call('RcppTest_asDouble', PACKAGE = 'RcppTest', d)
}

asInt <- function(i) {
    .Call('RcppTest_asInt', PACKAGE = 'RcppTest', i)
}

asStdString <- function(s) {
    .Call('RcppTest_asStdString', PACKAGE = 'RcppTest', s)
}

asRaw <- function(i) {
    .Call('RcppTest_asRaw', PACKAGE = 'RcppTest', i)
}

asLogical <- function(b) {
    .Call('RcppTest_asLogical', PACKAGE = 'RcppTest', b)
}

asStdVectorInt <- function(x) {
    .Call('RcppTest_asStdVectorInt', PACKAGE = 'RcppTest', x)
}

asStdVectorDouble <- function(x) {
    .Call('RcppTest_asStdVectorDouble', PACKAGE = 'RcppTest', x)
}

asStdVectorRaw <- function(x) {
    .Call('RcppTest_asStdVectorRaw', PACKAGE = 'RcppTest', x)
}

asStdVectorBool <- function(x) {
    .Call('RcppTest_asStdVectorBool', PACKAGE = 'RcppTest', x)
}

asStdVectorString <- function(x) {
    .Call('RcppTest_asStdVectorString', PACKAGE = 'RcppTest', x)
}

stdsetint <- function() {
    .Call('RcppTest_stdsetint', PACKAGE = 'RcppTest')
}

stdsetdouble <- function() {
    .Call('RcppTest_stdsetdouble', PACKAGE = 'RcppTest')
}

stdsetraw <- function() {
    .Call('RcppTest_stdsetraw', PACKAGE = 'RcppTest')
}

stdsetstring <- function() {
    .Call('RcppTest_stdsetstring', PACKAGE = 'RcppTest')
}

hasAttribute <- function(x) {
    .Call('RcppTest_hasAttribute', PACKAGE = 'RcppTest', x)
}

attr_ <- function(x) {
    .Call('RcppTest_attr_', PACKAGE = 'RcppTest', x)
}

attr_set <- function() {
    .Call('RcppTest_attr_set', PACKAGE = 'RcppTest')
}

isNULL <- function(x) {
    .Call('RcppTest_isNULL', PACKAGE = 'RcppTest', x)
}

inherits_ <- function(xx) {
    .Call('RcppTest_inherits_', PACKAGE = 'RcppTest', xx)
}

String_replace_all <- function(z, x, y) {
    .Call('RcppTest_String_replace_all', PACKAGE = 'RcppTest', z, x, y)
}

String_replace_first <- function(z, x, y) {
    .Call('RcppTest_String_replace_first', PACKAGE = 'RcppTest', z, x, y)
}

String_replace_last <- function(z, x, y) {
    .Call('RcppTest_String_replace_last', PACKAGE = 'RcppTest', z, x, y)
}

test_sapply_string <- function(text, old, new_) {
    .Call('RcppTest_test_sapply_string', PACKAGE = 'RcppTest', text, old, new_)
}

test_compare_Strings <- function(aa, bb) {
    .Call('RcppTest_test_compare_Strings', PACKAGE = 'RcppTest', aa, bb)
}

CharacterVector_wstring <- function() {
    .Call('RcppTest_CharacterVector_wstring', PACKAGE = 'RcppTest')
}

wstring_return <- function() {
    .Call('RcppTest_wstring_return', PACKAGE = 'RcppTest')
}

wstring_param <- function(s1, s2) {
    .Call('RcppTest_wstring_param', PACKAGE = 'RcppTest', s1, s2)
}

wrap_vector_wstring <- function() {
    .Call('RcppTest_wrap_vector_wstring', PACKAGE = 'RcppTest')
}

as_vector_wstring <- function(x) {
    .Call('RcppTest_as_vector_wstring', PACKAGE = 'RcppTest', x)
}

subset_test_int <- function(x, y) {
    .Call('RcppTest_subset_test_int', PACKAGE = 'RcppTest', x, y)
}

subset_test_lgcl <- function(x, y) {
    .Call('RcppTest_subset_test_lgcl', PACKAGE = 'RcppTest', x, y)
}

subset_test_char <- function(x, y) {
    .Call('RcppTest_subset_test_char', PACKAGE = 'RcppTest', x, y)
}

subset_test_greater_0 <- function(x) {
    .Call('RcppTest_subset_test_greater_0', PACKAGE = 'RcppTest', x)
}

subset_test_literal <- function(x) {
    .Call('RcppTest_subset_test_literal', PACKAGE = 'RcppTest', x)
}

subset_test_assign <- function(x) {
    .Call('RcppTest_subset_test_assign', PACKAGE = 'RcppTest', x)
}

runit_abs <- function(xx, yy) {
    .Call('RcppTest_runit_abs', PACKAGE = 'RcppTest', xx, yy)
}

runit_constructor <- function(xx, yy) {
    .Call('RcppTest_runit_constructor', PACKAGE = 'RcppTest', xx, yy)
}

runit_assignment <- function(xx, yy) {
    .Call('RcppTest_runit_assignment', PACKAGE = 'RcppTest', xx, yy)
}

runit_diff <- function(xx) {
    .Call('RcppTest_runit_diff', PACKAGE = 'RcppTest', xx)
}

runit_diff_int <- function(xx) {
    .Call('RcppTest_runit_diff_int', PACKAGE = 'RcppTest', xx)
}

runit_diff_ifelse <- function(pred, xx, yy) {
    .Call('RcppTest_runit_diff_ifelse', PACKAGE = 'RcppTest', pred, xx, yy)
}

runit_exp <- function(xx, yy) {
    .Call('RcppTest_runit_exp', PACKAGE = 'RcppTest', xx, yy)
}

runit_floor <- function(xx, yy) {
    .Call('RcppTest_runit_floor', PACKAGE = 'RcppTest', xx, yy)
}

runit_ceil <- function(xx, yy) {
    .Call('RcppTest_runit_ceil', PACKAGE = 'RcppTest', xx, yy)
}

runit_pow <- function(xx, yy) {
    .Call('RcppTest_runit_pow', PACKAGE = 'RcppTest', xx, yy)
}

runit_ifelse <- function(xx, yy) {
    .Call('RcppTest_runit_ifelse', PACKAGE = 'RcppTest', xx, yy)
}

runit_isna <- function(xx) {
    .Call('RcppTest_runit_isna', PACKAGE = 'RcppTest', xx)
}

runit_isfinite <- function(xx) {
    .Call('RcppTest_runit_isfinite', PACKAGE = 'RcppTest', xx)
}

runit_isinfinite <- function(xx) {
    .Call('RcppTest_runit_isinfinite', PACKAGE = 'RcppTest', xx)
}

runit_isnan <- function(xx) {
    .Call('RcppTest_runit_isnan', PACKAGE = 'RcppTest', xx)
}

runit_lapply <- function(xx) {
    .Call('RcppTest_runit_lapply', PACKAGE = 'RcppTest', xx)
}

runit_minus <- function(xx) {
    .Call('RcppTest_runit_minus', PACKAGE = 'RcppTest', xx)
}

runit_plus <- function(xx) {
    .Call('RcppTest_runit_plus', PACKAGE = 'RcppTest', xx)
}

runit_plus_seqlen <- function() {
    .Call('RcppTest_runit_plus_seqlen', PACKAGE = 'RcppTest')
}

runit_pmin <- function(xx, yy) {
    .Call('RcppTest_runit_pmin', PACKAGE = 'RcppTest', xx, yy)
}

runit_pmin_one <- function(xx) {
    .Call('RcppTest_runit_pmin_one', PACKAGE = 'RcppTest', xx)
}

runit_pmax <- function(xx, yy) {
    .Call('RcppTest_runit_pmax', PACKAGE = 'RcppTest', xx, yy)
}

runit_pmax_one <- function(xx) {
    .Call('RcppTest_runit_pmax_one', PACKAGE = 'RcppTest', xx)
}

runit_sapply <- function(xx) {
    .Call('RcppTest_runit_sapply', PACKAGE = 'RcppTest', xx)
}

runit_sapply_rawfun <- function(xx) {
    .Call('RcppTest_runit_sapply_rawfun', PACKAGE = 'RcppTest', xx)
}

runit_sapply_list <- function(xx) {
    .Call('RcppTest_runit_sapply_list', PACKAGE = 'RcppTest', xx)
}

runit_seqalong <- function(xx) {
    .Call('RcppTest_runit_seqalong', PACKAGE = 'RcppTest', xx)
}

runit_seqlen <- function() {
    .Call('RcppTest_runit_seqlen', PACKAGE = 'RcppTest')
}

runit_sign <- function(xx, yy) {
    .Call('RcppTest_runit_sign', PACKAGE = 'RcppTest', xx, yy)
}

runit_times <- function(xx) {
    .Call('RcppTest_runit_times', PACKAGE = 'RcppTest', xx)
}

runit_divides <- function(xx) {
    .Call('RcppTest_runit_divides', PACKAGE = 'RcppTest', xx)
}

runit_unary_minus <- function(xx) {
    .Call('RcppTest_runit_unary_minus', PACKAGE = 'RcppTest', xx)
}

runit_wrap <- function(xx, yy, e) {
    invisible(.Call('RcppTest_runit_wrap', PACKAGE = 'RcppTest', xx, yy, e))
}

runit_complex <- function(cx) {
    .Call('RcppTest_runit_complex', PACKAGE = 'RcppTest', cx)
}

runit_rep <- function(xx) {
    .Call('RcppTest_runit_rep', PACKAGE = 'RcppTest', xx)
}

runit_rev <- function(xx) {
    .Call('RcppTest_runit_rev', PACKAGE = 'RcppTest', xx)
}

runit_outer <- function(xx, yy) {
    .Call('RcppTest_runit_outer', PACKAGE = 'RcppTest', xx, yy)
}

runit_row <- function(xx) {
    .Call('RcppTest_runit_row', PACKAGE = 'RcppTest', xx)
}

runit_head <- function(xx) {
    .Call('RcppTest_runit_head', PACKAGE = 'RcppTest', xx)
}

runit_tail <- function(xx) {
    .Call('RcppTest_runit_tail', PACKAGE = 'RcppTest', xx)
}

runit_diag <- function(xx, mm) {
    .Call('RcppTest_runit_diag', PACKAGE = 'RcppTest', xx, mm)
}

runit_gamma <- function(xx) {
    .Call('RcppTest_runit_gamma', PACKAGE = 'RcppTest', xx)
}

runit_choose <- function(nn, kk) {
    .Call('RcppTest_runit_choose', PACKAGE = 'RcppTest', nn, kk)
}

runit_lchoose <- function(nn, kk) {
    .Call('RcppTest_runit_lchoose', PACKAGE = 'RcppTest', nn, kk)
}

runit_beta <- function(nn, kk) {
    .Call('RcppTest_runit_beta', PACKAGE = 'RcppTest', nn, kk)
}

runit_psigamma <- function(nn, kk) {
    .Call('RcppTest_runit_psigamma', PACKAGE = 'RcppTest', nn, kk)
}

runit_lbeta <- function(nn, kk) {
    .Call('RcppTest_runit_lbeta', PACKAGE = 'RcppTest', nn, kk)
}

runit_log1p <- function(xx) {
    .Call('RcppTest_runit_log1p', PACKAGE = 'RcppTest', xx)
}

runit_sum <- function(xx) {
    .Call('RcppTest_runit_sum', PACKAGE = 'RcppTest', xx)
}

runit_sum_cplx <- function(xx) {
    .Call('RcppTest_runit_sum_cplx', PACKAGE = 'RcppTest', xx)
}

runit_mean_cplx <- function(xx) {
    .Call('RcppTest_runit_mean_cplx', PACKAGE = 'RcppTest', xx)
}

runit_cumsum <- function(xx) {
    .Call('RcppTest_runit_cumsum', PACKAGE = 'RcppTest', xx)
}

runit_diff_REALSXP_NA <- function(x) {
    .Call('RcppTest_runit_diff_REALSXP_NA', PACKAGE = 'RcppTest', x)
}

runit_trunc <- function(xx, yy) {
    .Call('RcppTest_runit_trunc', PACKAGE = 'RcppTest', xx, yy)
}

runit_round <- function(xx, d) {
    .Call('RcppTest_runit_round', PACKAGE = 'RcppTest', xx, d)
}

runit_signif <- function(xx, d) {
    .Call('RcppTest_runit_signif', PACKAGE = 'RcppTest', xx, d)
}

runit_table <- function(x) {
    .Call('RcppTest_runit_table', PACKAGE = 'RcppTest', x)
}

runit_duplicated <- function(x) {
    .Call('RcppTest_runit_duplicated', PACKAGE = 'RcppTest', x)
}

runit_union <- function(x, y) {
    .Call('RcppTest_runit_union', PACKAGE = 'RcppTest', x, y)
}

runit_setdiff <- function(x, y) {
    .Call('RcppTest_runit_setdiff', PACKAGE = 'RcppTest', x, y)
}

runit_intersect <- function(x, y) {
    .Call('RcppTest_runit_intersect', PACKAGE = 'RcppTest', x, y)
}

runit_clamp <- function(a, x, b) {
    .Call('RcppTest_runit_clamp', PACKAGE = 'RcppTest', a, x, b)
}

vector_scalar_ops <- function(xx) {
    .Call('RcppTest_vector_scalar_ops', PACKAGE = 'RcppTest', xx)
}

vector_scalar_logical <- function(xx) {
    .Call('RcppTest_vector_scalar_logical', PACKAGE = 'RcppTest', xx)
}

vector_vector_ops <- function(xx, yy) {
    .Call('RcppTest_vector_vector_ops', PACKAGE = 'RcppTest', xx, yy)
}

vector_vector_logical <- function(xx, yy) {
    .Call('RcppTest_vector_vector_logical', PACKAGE = 'RcppTest', xx, yy)
}

complex_binary_sugar <- function(xx, yy) {
    .Call('RcppTest_complex_binary_sugar', PACKAGE = 'RcppTest', xx, yy)
}

raw_ <- function() {
    .Call('RcppTest_raw_', PACKAGE = 'RcppTest')
}

raw_REALSXP <- function(x) {
    .Call('RcppTest_raw_REALSXP', PACKAGE = 'RcppTest', x)
}

expression_ <- function() {
    .Call('RcppTest_expression_', PACKAGE = 'RcppTest')
}

expression_variadic <- function() {
    .Call('RcppTest_expression_variadic', PACKAGE = 'RcppTest')
}

expression_parse <- function() {
    .Call('RcppTest_expression_parse', PACKAGE = 'RcppTest')
}

expression_parseerror <- function() {
    .Call('RcppTest_expression_parseerror', PACKAGE = 'RcppTest')
}

complex_ <- function() {
    .Call('RcppTest_complex_', PACKAGE = 'RcppTest')
}

complex_CPLXSXP <- function(x) {
    .Call('RcppTest_complex_CPLXSXP', PACKAGE = 'RcppTest', x)
}

complex_INTSXP <- function(vec) {
    .Call('RcppTest_complex_INTSXP', PACKAGE = 'RcppTest', vec)
}

complex_REALSXP <- function(vec) {
    .Call('RcppTest_complex_REALSXP', PACKAGE = 'RcppTest', vec)
}

integer_ctor <- function() {
    .Call('RcppTest_integer_ctor', PACKAGE = 'RcppTest')
}

integer_INTSXP <- function(vec) {
    .Call('RcppTest_integer_INTSXP', PACKAGE = 'RcppTest', vec)
}

integer_names_set <- function() {
    .Call('RcppTest_integer_names_set', PACKAGE = 'RcppTest')
}

integer_names_get <- function(y) {
    .Call('RcppTest_integer_names_get', PACKAGE = 'RcppTest', y)
}

integer_names_indexing <- function(y) {
    .Call('RcppTest_integer_names_indexing', PACKAGE = 'RcppTest', y)
}

integer_zero <- function() {
    .Call('RcppTest_integer_zero', PACKAGE = 'RcppTest')
}

integer_create_zero <- function() {
    .Call('RcppTest_integer_create_zero', PACKAGE = 'RcppTest')
}

integer_create_ <- function() {
    .Call('RcppTest_integer_create_', PACKAGE = 'RcppTest')
}

integer_clone_ <- function(vec) {
    .Call('RcppTest_integer_clone_', PACKAGE = 'RcppTest', vec)
}

numeric_ <- function() {
    .Call('RcppTest_numeric_', PACKAGE = 'RcppTest')
}

numeric_REALSXP <- function(vec) {
    .Call('RcppTest_numeric_REALSXP', PACKAGE = 'RcppTest', vec)
}

list_ctor <- function() {
    .Call('RcppTest_list_ctor', PACKAGE = 'RcppTest')
}

list_template_ <- function() {
    .Call('RcppTest_list_template_', PACKAGE = 'RcppTest')
}

list_VECSXP_ <- function(vec) {
    .Call('RcppTest_list_VECSXP_', PACKAGE = 'RcppTest', vec)
}

list_iterator_ <- function(input, fun) {
    .Call('RcppTest_list_iterator_', PACKAGE = 'RcppTest', input, fun)
}

list_name_indexing <- function(df) {
    .Call('RcppTest_list_name_indexing', PACKAGE = 'RcppTest', df)
}

list_implicit_push_back <- function() {
    .Call('RcppTest_list_implicit_push_back', PACKAGE = 'RcppTest')
}

list_create_ <- function() {
    .Call('RcppTest_list_create_', PACKAGE = 'RcppTest')
}

list_stdcomplex <- function() {
    .Call('RcppTest_list_stdcomplex', PACKAGE = 'RcppTest')
}

character_ctor <- function() {
    .Call('RcppTest_character_ctor', PACKAGE = 'RcppTest')
}

character_STRSXP_ <- function(vec) {
    .Call('RcppTest_character_STRSXP_', PACKAGE = 'RcppTest', vec)
}

character_plusequals <- function() {
    .Call('RcppTest_character_plusequals', PACKAGE = 'RcppTest')
}

character_iterator1 <- function(letters) {
    .Call('RcppTest_character_iterator1', PACKAGE = 'RcppTest', letters)
}

character_iterator2 <- function(letters) {
    .Call('RcppTest_character_iterator2', PACKAGE = 'RcppTest', letters)
}

character_reverse <- function(y) {
    .Call('RcppTest_character_reverse', PACKAGE = 'RcppTest', y)
}

character_names_indexing <- function(y) {
    .Call('RcppTest_character_names_indexing', PACKAGE = 'RcppTest', y)
}

character_find_ <- function(y) {
    .Call('RcppTest_character_find_', PACKAGE = 'RcppTest', y)
}

character_create_ <- function() {
    .Call('RcppTest_character_create_', PACKAGE = 'RcppTest')
}

List_extract <- function(input) {
    .Call('RcppTest_List_extract', PACKAGE = 'RcppTest', input)
}

factors <- function(s) {
    .Call('RcppTest_factors', PACKAGE = 'RcppTest', s)
}

IntegerVector_int_init <- function() {
    .Call('RcppTest_IntegerVector_int_init', PACKAGE = 'RcppTest')
}

CharacterVectorEqualityOperator <- function(x, y) {
    .Call('RcppTest_CharacterVectorEqualityOperator', PACKAGE = 'RcppTest', x, y)
}

List_rep_ctor <- function(x) {
    .Call('RcppTest_List_rep_ctor', PACKAGE = 'RcppTest', x)
}

stdVectorDouble <- function(x) {
    .Call('RcppTest_stdVectorDouble', PACKAGE = 'RcppTest', x)
}

stdVectorDoubleConst <- function(x) {
    .Call('RcppTest_stdVectorDoubleConst', PACKAGE = 'RcppTest', x)
}

stdVectorDoubleRef <- function(x) {
    .Call('RcppTest_stdVectorDoubleRef', PACKAGE = 'RcppTest', x)
}

stdVectorDoubleConstRef <- function(x) {
    .Call('RcppTest_stdVectorDoubleConstRef', PACKAGE = 'RcppTest', x)
}

stdVectorInt <- function(x) {
    .Call('RcppTest_stdVectorInt', PACKAGE = 'RcppTest', x)
}

stdVectorIntConst <- function(x) {
    .Call('RcppTest_stdVectorIntConst', PACKAGE = 'RcppTest', x)
}

stdVectorIntRef <- function(x) {
    .Call('RcppTest_stdVectorIntRef', PACKAGE = 'RcppTest', x)
}

stdVectorIntConstRef <- function(x) {
    .Call('RcppTest_stdVectorIntConstRef', PACKAGE = 'RcppTest', x)
}

character_vector_const_proxy <- function(str) {
    .Call('RcppTest_character_vector_const_proxy', PACKAGE = 'RcppTest', str)
}

CharacterVector_test_const_proxy <- function(x) {
    .Call('RcppTest_CharacterVector_test_const_proxy', PACKAGE = 'RcppTest', x)
}

map_string_int <- function() {
    .Call('RcppTest_map_string_int', PACKAGE = 'RcppTest')
}

map_string_double <- function() {
    .Call('RcppTest_map_string_double', PACKAGE = 'RcppTest')
}

map_string_bool <- function() {
    .Call('RcppTest_map_string_bool', PACKAGE = 'RcppTest')
}

map_string_Rbyte <- function() {
    .Call('RcppTest_map_string_Rbyte', PACKAGE = 'RcppTest')
}

map_string_string <- function() {
    .Call('RcppTest_map_string_string', PACKAGE = 'RcppTest')
}

map_string_generic <- function() {
    .Call('RcppTest_map_string_generic', PACKAGE = 'RcppTest')
}

multimap_string_int <- function() {
    .Call('RcppTest_multimap_string_int', PACKAGE = 'RcppTest')
}

multimap_string_double <- function() {
    .Call('RcppTest_multimap_string_double', PACKAGE = 'RcppTest')
}

multimap_string_bool <- function() {
    .Call('RcppTest_multimap_string_bool', PACKAGE = 'RcppTest')
}

multimap_string_Rbyte <- function() {
    .Call('RcppTest_multimap_string_Rbyte', PACKAGE = 'RcppTest')
}

multimap_string_string <- function() {
    .Call('RcppTest_multimap_string_string', PACKAGE = 'RcppTest')
}

multimap_string_generic <- function() {
    .Call('RcppTest_multimap_string_generic', PACKAGE = 'RcppTest')
}

nonnull_const_char <- function() {
    .Call('RcppTest_nonnull_const_char', PACKAGE = 'RcppTest')
}

map_int_double <- function() {
    .Call('RcppTest_map_int_double', PACKAGE = 'RcppTest')
}

map_double_double <- function() {
    .Call('RcppTest_map_double_double', PACKAGE = 'RcppTest')
}

map_int_vector_double <- function() {
    .Call('RcppTest_map_int_vector_double', PACKAGE = 'RcppTest')
}

wrap_auto_create <- function() {
    .Call('RcppTest_wrap_auto_create', PACKAGE = 'RcppTest')
}

xptr_1 <- function() {
    .Call('RcppTest_xptr_1', PACKAGE = 'RcppTest')
}

xptr_2 <- function(p) {
    .Call('RcppTest_xptr_2', PACKAGE = 'RcppTest', p)
}
